### ISSUE TITLE
Can't start server because of permission denied

### ISSUE THREAD

**Issue by PascalMinder** [Didstopia/7dtd-server#30]
I use the following command to create the server:

```
docker run -d \
   --name=7d2d \
   -e PUID=1000 \
   -e PGID=100 \
   -e TZ=Europe/Zurich \
   -v /sharedfolders/docker/config/7d2d/steam:/steamcmd/7dtd \
   -v /sharedfolders/docker/config/7d2d/game:/app/.local/share/7DaysToDie \
   -p 26900-26902:26900-26902 \
   -p 26900-26902:26900-26902/udp \
   didstopia/7dtd-server
```
This leads to creation of two folders `game` and `steam`. The `game` folder has the right user permissions, while the `steam` folder has `root:root`. This leads to the error:

> /app/start.sh: line 116: /steamcmd/7dtd/7DaysToDieServer.x86_64: Permission denied

**Comment by Dids** [comment]
Both volumes need to be set to the same user id (`PUID`) and group id (`PGID`).

**Comment by PascalMinder** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/1893516/76709700-c1f1e700-66f8-11ea-92c8-0c0730a7ee27.png">

Yes they are. But still the same error

**Comment by Dids** [comment]
Just to be sure, did your run `chown -R` to apply the permissions recursively?

I'll be deploying a potential fix upstream to the base images, which should fix this automagically. I'll let you know when the fix is live.

**Comment by Dids** [comment]
Okay, can you pull the latest version and give that one a go? It should now always fix the permissions on startup, so long as you're not using any custom container paths, outside of `/steamcmd` and `/app`.

**Comment by PascalMinder** [comment]
I will try it tonight. Thanks

**Comment by PascalMinder** [comment]
Hmm, I still have the same error. Is there any way to get more error information? I am trying to run it on an OMV host.

**Comment by Dids** [comment]
Could you try deleting the volumes/folders again? Both `game` and `steam` should now be under the non-root user, and the permissions are set whenever the container starts. Additionally, could you try running the container as root, if the previous attempt fails? Just `sudo docker run ...` should do, just to rule out anything else.

**Comment by PascalMinder** [comment]
I will try it tonight. Sorry for the late reply.

**Comment by PascalMinder** [comment]
So I tried it again tonight. First I deleted everything. Then I created both folders:
![image](https://user-images.githubusercontent.com/1893516/76998651-62404980-694d-11ea-8875-fc4866ceed2f.png)
After that I created the container with the following:
```
docker run -d \
   --name=7d2d \
   -e PUID=1000 \
   -e PGID=100 \
   -e TZ=Europe/Zurich \
   -v /sharedfolders/docker/config/7d2d/steam:/steamcmd/7dtd \
   -v /sharedfolders/docker/config/7d2d/game:/app/.local/share/7DaysToDie \
   -p 26900-26902:26900-26902 \
   -p 26900-26902:26900-26902/udp \
   didstopia/7dtd-server 
```
![image](https://user-images.githubusercontent.com/1893516/76998747-7dab5480-694d-11ea-93be-7e701256f978.png)
![image](https://user-images.githubusercontent.com/1893516/76998754-813edb80-694d-11ea-977a-52608e0c09d2.png)
![image](https://user-images.githubusercontent.com/1893516/76998760-83089f00-694d-11ea-8943-8c196725f285.png)

Could it be that somehow the platforms are incompatible?

![image](https://user-images.githubusercontent.com/1893516/76998931-c236f000-694d-11ea-80ba-ed8ae42f46ff.png)

![image](https://user-images.githubusercontent.com/1893516/76999052-fd392380-694d-11ea-9dfd-475acfca7f32.png)

**Comment by Dids** [comment]
Have you tried without creating the folders manually? Because Docker should ideally be in charge of creating them, as then it could also set the permissions accordingly.

**Comment by PascalMinder** [comment]
I might have found the issue. `cat /etc/mtab` gives me:
`/dev/md0 /home/steam/7d2d/server ext4 rw,noexec,relatime,stripe=384,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group 0 0
/dev/md0 /home/steam/7d2d/save ext4 rw,noexec,relatime,stripe=384,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group 0 0`

I think the problem is `noexec`

**Comment by Dids** [comment]
It's possible, but then `noexec` should be coming from the filesystem/partition mount flags and there's not much Docker can do about it.

**Comment by PascalMinder** [comment]
Yeah, OMV does this for the data partition. So I guess it's my error. Sorry.

**Comment by Dids** [comment]
No worries! As a last resort, you could try again, but this time with `PUID=0` and `PGID=0`, which would effectively run the container as root again.
